CompanyCrm/Controllers/AddressesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using CustomerModels;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;

namespace CompanyCrm.Controllers
{
    public class AddressesController : Controller
    {
        private readonly IHttpClientFactory _httpClientFactory;

        public AddressesController(IHttpClientFactory httpClientFactory)
        {
            _httpClientFactory = httpClientFactory;
        }

        [HttpGet]
        public async Task<ActionResult<AddressModel[]>> List(int id)
        {
            var httpClient = _httpClientFactory.CreateClient("CompanyCrmClient");

            HttpRequestMessage request = new HttpRequestMessage(HttpMethod.Get, $"addresses/GetByCustomer/{id}");
            HttpResponseMessage response = await httpClient.SendAsync(request);
            response.EnsureSuccessStatusCode();

            string content = await response.Content.ReadAsStringAsync();
            //IEnumerable<AddressModel> addresses = JsonConvert.DeserializeObject<IEnumerable<AddressModel>>(content);  *** Converted from IEnum<AddrModel> to AddrModel[] for testing
            AddressModel[] addresses = JsonConvert.DeserializeObject<AddressModel[]>(content);

            return View(addresses);
        }

        [HttpGet]
        public async Task<ActionResult<AddressModel>> Details(int id)
        {
            var httpClient = _httpClientFactory.CreateClient("CompanyCrmClient");

            HttpRequestMessage request = new HttpRequestMessage(HttpMethod.Get, $"addresses/{id}");
            HttpResponseMessage response = await httpClient.SendAsync(request);
            response.EnsureSuccessStatusCode();

            string content = await response.Content.ReadAsStringAsync();
            AddressModel address = JsonConvert.DeserializeObject<AddressModel>(content);

            return View("Details", address);
        }

        [HttpGet]
        public async Task<ActionResult<AddressCreateViewModel>> Create(int id)
        {
            var httpClient = _httpClientFactory.CreateClient("CompanyCrmClient");

            HttpRequestMessage request = new HttpRequestMessage(HttpMethod.Get, "addresses/GetAllCountries");
            HttpResponseMessage response = await httpClient.SendAsync(request);
            response.EnsureSuccessStatusCode();

            string content = await response.Content.ReadAsStringAsync();
            Country[] countries = JsonConvert.DeserializeObject<Country[]>(content);

            List<SelectListItem> countriesList = countries
           .OrderBy(c => c.Name)
           .Select(c => new SelectListItem
           {
               Value = c.CountryCode.ToString(),
               Text = c.Name
           })
           .ToList();
            var countrytip = new SelectListItem()
            {
                Value = null,
                Text = "--- select country ---"
            };
            countriesList.Insert(0, countrytip);

            IEnumerable<SelectListItem> regions = new List<SelectListItem>()
            {
                new SelectListItem
                {
                    Value = null,
                    Text = " "
                }
            };

        AddressCreateViewModel newAddress = new AddressCreateViewModel()
            {
                CustomerId = id,
                Countries = countriesList,
                Regions = regions
            };

            return View(newAddress);
        }

        [HttpGet]
        public async Task<ActionResult> GetRegions(string countryCode)
        {
            if (!string.IsNullOrWhiteSpace(countryCode) && countryCode.Length == 2)
            {
                var httpClient = _httpClientFactory.CreateClient("CompanyCrmClient");

                HttpRequestMessage request = new HttpRequestMessage(HttpMethod.Get, $"addresses/GetRegions/{countryCode}");
                HttpResponseMessage response = await httpClient.SendAsync(request);
                response.EnsureSuccessStatusCode();

                string content = await response.Content.ReadAsStringAsync();
                
                // need to find regions that match country code parameter
                Region[] associatedRegions = JsonConvert.DeserializeObject<Region[]>(content);

                // Change model.Countries into SelectList
                IEnumerable<SelectListItem> results = associatedRegions
                    .OrderBy(r => r.Name)
                    .Select(r => new SelectListItem
                    {
                        Value = r.Name,
                        Text = r.Name
                    })
                    .ToList();

                var regions = new SelectList(results, "Value", "Text");
                return Json(regions);
            }

            return null;
        }

        [HttpPost]
        public async Task<ActionResult<AddressModel>> Create(AddressModel address)
        {
            var httpClient = _httpClientFactory.CreateClient("CompanyCrmClient");
            
            string newAddress = JsonConvert.SerializeObject(address);

            HttpRequestMessage request = new HttpRequestMessage(HttpMethod.Post, $"addresses");
            request.Content = new StringContent(newAddress);
            request.Content.Headers.ContentType = new MediaTypeHeaderValue("application/json");
            HttpResponseMessage response = await httpClient.SendAsync(request);
            response.EnsureSuccessStatusCode();

            return RedirectToAction("Details", "Customers", new { id = address.CustomerId} );
        }

        [HttpGet]
        public async Task<ActionResult<AddressModel>> Delete(int id)
        {
            var httpClient = _httpClientFactory.CreateClient("CompanyCrmClient");
            
            HttpRequestMessage request = new HttpRequestMessage(HttpMethod.Get, $"addresses/{id}");
            HttpResponseMessage response = await httpClient.SendAsync(request);
            response.EnsureSuccessStatusCode();

            string content = await response.Content.ReadAsStringAsync();
            AddressModel address = JsonConvert.DeserializeObject<AddressModel>(content);

            return View(address);
        }

        [HttpPost]
        public async Task<IActionResult> Delete(AddressModel address)
        {
            var httpClient = _httpClientFactory.CreateClient("CompanyCrmClient");

            HttpRequestMessage request = new HttpRequestMessage(HttpMethod.Delete, $"addresses/{address.AddressId}");
            HttpResponseMessage response = await httpClient.SendAsync(request);
            response.EnsureSuccessStatusCode();

            return RedirectToAction("Details", "Customers", new { id = address.CustomerId });
        }
    }
}

CompanyCrm/Controllers/CustomersController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using CustomerModels;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;

namespace CompanyCrm.Controllers
{
    [Authorize]
    public class CustomersController : Controller
    {
        private readonly IHttpClientFactory _httpClientFactory;

        public CustomersController(IHttpClientFactory httpClientFactory)
        {
            _httpClientFactory = httpClientFactory;
        }

        [HttpGet]
        public async Task<ActionResult<CustomerModel[]>> List()
        {
            var httpClient = _httpClientFactory.CreateClient("CompanyCrmClient");

            string userId = User.FindFirst(ClaimTypes.NameIdentifier).Value;

            HttpRequestMessage request = new HttpRequestMessage(HttpMethod.Get, $"customers/{userId}");
            HttpResponseMessage response = await httpClient.SendAsync(request);
            response.EnsureSuccessStatusCode();

            string content = await response.Content.ReadAsStringAsync();
            IEnumerable<CustomerModel> customers = JsonConvert.DeserializeObject<IEnumerable<CustomerModel>>(content);

            return View(customers);
        }

        [HttpGet]
        public async Task<ActionResult<CustomerModel>> Details(int id)
        {
            var httpClient = _httpClientFactory.CreateClient("CompanyCrmClient");
         
            HttpRequestMessage request = new HttpRequestMessage(HttpMethod.Get, $"customers/{id}");
            HttpResponseMessage response = await httpClient.SendAsync(request);

            if (response.StatusCode == System.Net.HttpStatusCode.NotFound)
            {
                return NotFound();
            }

            response.EnsureSuccessStatusCode();

            string content = await response.Content.ReadAsStringAsync();
            CustomerModel customer = JsonConvert.DeserializeObject<CustomerModel>(content);

            return View("Details", customer);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult<CustomerModel>> Create(CustomerModel newCustomer)
        {
            try
            {
                var httpClient = _httpClientFactory.CreateClient("CompanyCrmClient");
                
                string userId = User.FindFirst(ClaimTypes.NameIdentifier).Value;
                newCustomer.UserId = userId;

                string customerString = JsonConvert.SerializeObject(newCustomer);

                HttpRequestMessage request = new HttpRequestMessage(HttpMethod.Post, "customers");
                request.Content = new StringContent(customerString);
                request.Content.Headers.ContentType = new MediaTypeHeaderValue("application/json");

                HttpResponseMessage response = await httpClient.SendAsync(request);
                response.EnsureSuccessStatusCode();

                return RedirectToAction("List");
            }
            catch
            {
                return View();
            }
        }

        [HttpGet]
        public async Task<ActionResult<CustomerModel>> Update(int id)
        {
            try
            {
                var httpClient = _httpClientFactory.CreateClient("CompanyCrmClient");
                
                HttpRequestMessage request = new HttpRequestMessage(HttpMethod.Get, $"customers/{id}");
                HttpResponseMessage response = await httpClient.SendAsync(request);
                response.EnsureSuccessStatusCode();

                string content = await response.Content.ReadAsStringAsync();
                CustomerModel customer = JsonConvert.DeserializeObject<CustomerModel>(content);

                return View(customer);
            }
            catch (Exception)
            {
                return View();
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Update(CustomerModel customer)
        {
            try
            {
                var httpClient = _httpClientFactory.CreateClient("CompanyCrmClient");

                string customerToUpdate = JsonConvert.SerializeObject(customer);

                HttpRequestMessage request = new HttpRequestMessage(HttpMethod.Put, $"customers/{customer.CustomerId}");
                request.Content = new StringContent(customerToUpdate);
                request.Content.Headers.ContentType = new MediaTypeHeaderValue("application/json");

                HttpResponseMessage response = await httpClient.SendAsync(request);
                response.EnsureSuccessStatusCode();

                string content = await response.Content.ReadAsStringAsync();
                CustomerModel updatedCustomer = JsonConvert.DeserializeObject<CustomerModel>(content);

                return View("Details", updatedCustomer);
            }
            catch
            {
                return View("Update");
            }
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            try
            {
                var httpClient = _httpClientFactory.CreateClient("CompanyCrmClient");

                HttpRequestMessage request = new HttpRequestMessage(HttpMethod.Get, $"customers/{id}");
                HttpResponseMessage response = await httpClient.SendAsync(request);
                response.EnsureSuccessStatusCode();

                string content = await response.Content.ReadAsStringAsync();
                CustomerModel customer = JsonConvert.DeserializeObject<CustomerModel>(content);

                return View(customer);
            }
            catch (Exception)
            {
                return View();
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int id, IFormCollection collection)
        {
            try
            {
                var httpClient = _httpClientFactory.CreateClient("CompanyCrmClient");

                HttpRequestMessage request = new HttpRequestMessage(HttpMethod.Delete, $"customers/{id}");
                HttpResponseMessage response = await httpClient.SendAsync(request);
                response.EnsureSuccessStatusCode();

                return RedirectToAction("List");
            }
            catch
            {
                return View("Delete");
            }
        }
    }
}

CompanyCrm/Views/Customers/Create.cshtml
@model CustomerModel

<form asp-action="Create" method="post" class="form-horizontal" role="form">
    <h4>Enter new customer below:</h4>

    <div class="form-group">
        <label asp-for="FirstName" class="col-md-2 control-label"></label>
        <div class="col-md-5">
            <input asp-for="FirstName" class="form-control" />
        </div>
        <span asp-validation-for="FirstName" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="LastName" class="col-md-2 control-label"></label>
        <div class="col-md-5">
            <input asp-for="LastName" class="form-control" />
        </div>
        <span asp-validation-for="LastName" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Age" class="col-md-2 control-label"></label>
        <div class="col-md-5">
            <input asp-for="Age" class="form-control" />
        </div>
        <span asp-validation-for="Age" class="text-danger"></span>
    </div>

    <div class="form-group">
        @foreach (Gender gender in Enum.GetValues(typeof(Gender)))
        {
            <input type="radio" asp-for="Gender" value="@gender" />@gender<br />
        }
    </div>

    <div class="form-group">
        <select asp-for="Education" asp-items="Html.GetEnumSelectList<Education>()">
            <option value="">Highest Level of Education Completed</option>
        </select>
    </div>

    <div class="form-group">
        <label asp-for="Interests" class="col-md-2 control-label"></label>
        <div class="col-md-5">
            <input asp-for="Interests" class="form-control" />
        </div>
        <span asp-validation-for="Interests" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Phone" class="col-md-2 control-label"></label>
        <div class="col-md-5">
            <input asp-for="Phone" class="form-control" />
        </div>
        <span asp-validation-for="Phone" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Email" class="col-md-2 control-label"></label>
        <div class="col-md-5">
            <input asp-for="Email" class="form-control" />
        </div>
        <span asp-validation-for="Email" class="text-danger"></span>
    </div>

    <div>
        <label value="Accept" class="col-md-2 control-label">I agree to the Terms of Service</label>
        <div class="col-md-5">
            <input type="checkbox" value="false" required />
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-2 col-md-5">
            <input type="submit" class="btn btn-primary" value="Submit" />
        </div>
    </div>
</form>

CompanyCrm/Views/Customers/Delete.cshtml
@model CustomerModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this customer?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CustomerId)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CustomerId)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Age)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Age)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Gender)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Gender)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Education)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Education)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Interests)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Interests)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Phone)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Phone)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.DateSubmitted)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.DateSubmitted)
        </dd>
    </dl>

    <form asp-action="Delete">
        @Html.AntiForgeryToken()

        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="List">Back to List</a>
    </form>
</div>

CompanyCrm/Views/Customers/Details.cshtml
@model CustomerModel

<h2>@Model.FullName</h2>

<div class="thumbnail">
    <div class="caption-full">
        <table>
            <tr>
                <th>Id</th>
                <td>@Model.CustomerId</td>
            </tr>
            <tr>
                <th>First Name</th>
                <td>@Model.FirstName</td>
            </tr>
            <tr>
                <th>Last Name</th>
                <td>@Model.LastName</td>
            </tr>
            <tr>
                <th>Age</th>
                <td>@Model.Age</td>
            </tr>
            <tr>
                <th>Gender</th>
                <td>@Model.Gender</td>
            </tr>
            <tr>
                <th>Education Level</th>
                <td>@Model.Education</td>
            </tr>
            <tr>
                <th>Interests</th>
                <td>@Model.Interests</td>
            </tr>
            <tr>
                <th>Phone</th>
                <td>@Model.Phone</td>
            </tr>
            <tr>
                <th>Email</th>
                <td>@Model.Email</td>
            </tr>
            <tr>
                <th>Date Submitted</th>
                <td>@Model.DateSubmitted</td>
            </tr>
        </table>
        <br>
        <div><a asp-controller="Addresses" asp-action="Create" asp-route-id="@Model.CustomerId">Add New Address</a></div>
        <table class="table">
            <thead>
                <tr>
                    <th>
                        Address Type
                    </th>
                    <th>
                        Address
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var address in Model.Addresses)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => address.AddressType)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => address.StreetLine1)
                        </td>
                        <td>
                            <a asp-action="Details" asp-controller="Addresses" asp-route-id="@address.AddressId">Details</a> |
                            <a asp-action="Delete" asp-controller="Addresses" asp-route-id="@address.AddressId">Delete</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
        <span><a asp-action="List">Back to Customer List</a></span>
    </div>
</div>

CompanyCrm/Views/Customers/List.cshtml
@model IEnumerable<CustomerModel>

@{
    ViewData["Title"] = "Customer List";
}

<h1>List</h1>
<h4>Total Customers: @Model.Count()</h4>
<p>
    <a asp-action="Create">Add New Customer</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>Name</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var customer in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => customer.FullName)
                </td>
                <td>
                    <a asp-action="Update" asp-route-id="@customer.CustomerId">Update</a> |
                    <a asp-action="Details" asp-route-id="@customer.CustomerId">Details</a> |
                    <a asp-action="Delete" asp-route-id="@customer.CustomerId">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

@if (User.Identity.IsAuthenticated)
{
    <table class="table table-sm">
        @foreach (var claim in User.Claims)
        {
            <tr>
                <td>@claim.Type</td>
                <td>@claim.Value</td>
            </tr>
        }
    </table>
}

CompanyCrm/Views/Customers/Update.cshtml
@model CustomerModel

@using (Html.BeginForm("Update", "Customers", FormMethod.Post,
new { @class = "form-horizontal", role = "form" }))
{
    @Html.HiddenFor(c => c.CustomerId);

    <h4>Update customer information below:</h4>

    <div class="form-group">
        <label asp-for="UserId" class="col-md-2 control-label"></label>
        <div class="col-md-5">
            <input asp-for="UserId" class="form-control" readonly="@(true)" />
        </div>
        <span asp-validation-for="UserId" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="FirstName" class="col-md-2 control-label"></label>
        <div class="col-md-5">
            <input asp-for="FirstName" class="form-control" />
        </div>
        <span asp-validation-for="FirstName" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="LastName" class="col-md-2 control-label"></label>
        <div class="col-md-5">
            <input asp-for="LastName" class="form-control" />
        </div>
        <span asp-validation-for="LastName" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Age" class="col-md-2 control-label"></label>
        <div class="col-md-5">
            <input asp-for="Age" class="form-control" />
        </div>
        <span asp-validation-for="Age" class="text-danger"></span>
    </div>

    <div class="form-group">
        @foreach (Gender gender in Enum.GetValues(typeof(Gender)))
        {
            <input type="radio" asp-for="Gender" value="@gender" />@gender<br />
        }
    </div>

    <div class="form-group">
        <select asp-for="Education" asp-items="Html.GetEnumSelectList<Education>()">
            <option value="">Highest Level of Education Completed</option>
        </select>
    </div>

    <div class="form-group">
        <label asp-for="Interests" class="col-md-2 control-label"></label>
        <div class="col-md-5">
            <input asp-for="Interests" class="form-control" />
        </div>
        <span asp-validation-for="Interests" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Phone" class="col-md-2 control-label"></label>
        <div class="col-md-5">
            <input asp-for="Phone" class="form-control" />
        </div>
        <span asp-validation-for="Phone" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Email" class="col-md-2 control-label"></label>
        <div class="col-md-5">
            <input asp-for="Email" class="form-control" />
        </div>
        <span asp-validation-for="Email" class="text-danger"></span>
    </div>

    <div>
        <label value="Accept" class="col-md-2 control-label">I agree to the Terms of Service</label>
        <div class="col-md-5">
            <input type="checkbox" value="false" required />
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-2 col-md-5">
            <input type="submit" class="btn btn-primary" value="Update" />
        </div>
    </div>
    <a asp-action="List">Back to List</a>
}